"""Generate committed OpenAPI JSON and TypeScript DTOs from the FastAPI application."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from camcat.api import app

ROOT = Path(__file__).resolve().parents[1]


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=False) for item in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "object":
        properties = schema.get("properties")
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        fields = [
            f"  {json.dumps(name)}{'?' if name not in required else ''}: {ts_type(value)};"
            for name, value in properties.items()
        ]
        return "{\n" + "\n".join(fields) + "\n}"
    return "string" if kind == "string" else "unknown"


def main() -> None:
    schema = app.openapi()
    contract_dir = ROOT / "packages" / "contracts"
    generated_dir = ROOT / "apps" / "web" / "src" / "generated"
    contract_dir.mkdir(parents=True, exist_ok=True)
    generated_dir.mkdir(parents=True, exist_ok=True)
    (contract_dir / "openapi.json").write_text(
        json.dumps(schema, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    definitions = schema.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by scripts/generate_openapi_contracts.py; do not edit manually.",
        "",
    ]
    for name in sorted(definitions):
        lines.append(f"export type {name} = {ts_type(definitions[name])};")
        lines.append("")
    (generated_dir / "api.ts").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
